apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      labels:
        app: test-app
    spec:
      containers:
        - name: test-app
          image: hanh1107/test-app:ad18c38998e6ebedb3e82a98e292383a1bf38c65
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-service
spec:
  selector:
    app: test-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-app-config
data:
  VERSION: "2.0.0"
